name: Dotnet HTTPS Test

on: [push]

jobs:
  test-https:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install required packages explicitly
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3-tools

    - name: Run HTTPS Test script
      run: |
        chmod +x ./gha-https-test.sh
        ./gha-https-test.sh
