name: Dotnet HTTPS Test

on: [push]

jobs:
  test-https:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3-tools

    - name: Set up Google Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'
        install-dependencies: true

    - name: Run HTTPS Test script
      run: |
        chmod +x ./gha-https-test.sh
        ./gha-https-test.sh

    - name: Display generated certificate files
      run: |
        echo "-----BEGIN Localhost CA Certificate-----"
        cat my-aspnet-app/localhost-ca.crt
        echo "-----END Localhost CA Certificate-----"

        echo "-----BEGIN Localhost Server Certificate-----"
        cat my-aspnet-app/localhost.crt
        echo "-----END Localhost Server Certificate-----"

        echo "-----BEGIN appsettings.json-----"
        cat my-aspnet-app/appsettings.json
        echo "-----END appsettings.json-----"
